sudo: false
language: ruby
rvm:
- 2.3.4
branches:
  only:
    - master
addons:
  apt:
    packages:
    - graphviz
    - openjdk-7-jre
script: ./_travis/build
bundler_args: --without development --deployment
