# Do not use tabs in this file!
repository: https://github.com/candlepin/candlepin

# Required for running on Ruby 1.9
encoding: utf-8

# Change this if we ever need the site to reside in a sub-directory
baseurl: ''

exclude: ['bin', 'Gemfile*', 'README.md', 'config.ru', 'vendor']
# The order of the categories here will be the order they show up in on the index page
projects_dir: 'docs'

# The tilde is YAML for nil.  Categories not in this map get nil and placed at the end.
category-order: {usage: 1, developers: 2, design: 3, uncategorized: ~}

permalink: /news/:year/:title.html
paginate: 8
paginate_path: /news/page:num

# What to compile with lessc
less_artifacts: ['assets/candlepin.less']
# -x minifies the CSS
lessc: bin/less.js-1.7.0/lessc -x

# This is a workaround so we can use pygments.rb
# See https://github.com/navarroj/krampygs
markdown_ext: dummy_value
markdown: kramdown
kramdown:
  # Use GitHub flavor markdown
  input: GFM
  hard_wrap: false
