# Do not use tabs in this file!
repository: https://github.com/candlepin/candlepin
exclude: ['bin', 'Gemfile*', 'README']
# The order of the categories here will be the order they show up in on the index page
projects_dir: 'docs'
category-weight: {usage: 0, developers: 1, design: 2, uncategorized: nil}

permalink: /news/:year/:title.html
paginate: 8
paginate_path: /news/page:num

# What to compile with lessc
less_artifacts: ['assets/candlepin.less']
# -x minifies the CSS
lessc: bin/less.js-1.7.0/lessc -x

# This is a workaround so we can use pygments.rb
# See https://github.com/navarroj/krampygs
markdown_ext: dummy_value
markdown: kramdown
kramdown:
  # Use GitHub flavor markdown
  input: GFM
  hard_wrap: false
